# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tech0-pos-api-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d9989eec89704b56b33da9b151948dba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e12bd2096a246fb92ec57cfeb3abfa2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d9989eec89704b56b33da9b151948dba }}/techo-pos:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tech0-pos-api-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a21b755949744be884f9ad2e3693b148 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d9989eec89704b56b33da9b151948dba }}/techo-pos:${{ github.sha }}'